inprog

diff --git a/bash/writeToStdinOfBackgroundProcess/Makefile b/bash/writeToStdinOfBackgroundProcess/Makefile
--- a/bash/writeToStdinOfBackgroundProcess/Makefile
+++ b/bash/writeToStdinOfBackgroundProcess/Makefile
@@ -1,7 +1,46 @@
+include mkutil/bash
+include mkutil/begin
 
-info:
-	if [[ ]]
-	bash -c 'cat serv-info/serv-input-cat-pid | tee >(cat 1>&2) | x echo "ps f {}" | grep -C3 '
+cmd :=
+d := proc
+$(shell mkdir -p $(d))
+
+# --------------------------------------------------------------------------------
+
+bg: $(cmd).check $d/$(cmd).in $d/$(cmd).in.pid
+	$(begin)
+	echo cmd=$(cmd)
+	cat $d/$(cmd).in | $(cmd) &
+
+$d/$(cmd).in:
+	$(begin)
+	mkfifo $@
+
+$d/$(cmd).in.pid: $d/$(cmd).in
+	$(begin)
+	cat > $< & echo $$! > $@
+
+$(cmd).check:
+	$(begin)
+	$(if $(cmd),,echo $$'\nError!\n- variable cmd must be defined!' && exit 1)
+
+info: cmd 
+	export cmd='$(shell cat $<)' \
+	&& echo "- cmd=$${cmd}" \
+	&& if [[ -f $${cmd}.input.pid ]]; then \
+	     echo "- cmd.in.pid file: exists" \
+	     && if pgrep $$(cat $${cmd}.input.pid); then \
+	       echo '- process is alive' ; \
+	     else \
+	       echo '- process is dead' ; \
+	     fi ; \
+	   else \
+	     echo "- cmd.in.pid file: do not exists"; \
+	   fi
+
+
+
+# bash -c 'cat serv-info/serv-input-cat-pid | tee >(cat 1>&2) | x echo "ps f {}" | grep -C3 '
 
 
 
